// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// ppmErr
double ppmErr(double m, double m0);
RcppExport SEXP _wSIMCity_ppmErr(SEXP mSEXP, SEXP m0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type m0(m0SEXP);
    rcpp_result_gen = Rcpp::wrap(ppmErr(m, m0));
    return rcpp_result_gen;
END_RCPP
}
// getMassTolRange
NumericVector getMassTolRange(long double m, long double ppm);
RcppExport SEXP _wSIMCity_getMassTolRange(SEXP mSEXP, SEXP ppmSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< long double >::type m(mSEXP);
    Rcpp::traits::input_parameter< long double >::type ppm(ppmSEXP);
    rcpp_result_gen = Rcpp::wrap(getMassTolRange(m, ppm));
    return rcpp_result_gen;
END_RCPP
}
// dlaplace
NumericVector dlaplace(NumericVector X, double m, double b);
RcppExport SEXP _wSIMCity_dlaplace(SEXP XSEXP, SEXP mSEXP, SEXP bSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type m(mSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    rcpp_result_gen = Rcpp::wrap(dlaplace(X, m, b));
    return rcpp_result_gen;
END_RCPP
}
// weight_laplace
NumericVector weight_laplace(NumericVector dM, double mu, double tol, double boost);
RcppExport SEXP _wSIMCity_weight_laplace(SEXP dMSEXP, SEXP muSEXP, SEXP tolSEXP, SEXP boostSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type dM(dMSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type boost(boostSEXP);
    rcpp_result_gen = Rcpp::wrap(weight_laplace(dM, mu, tol, boost));
    return rcpp_result_gen;
END_RCPP
}
// load_msdial_results
List load_msdial_results(DataFrame df);
RcppExport SEXP _wSIMCity_load_msdial_results(SEXP dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type df(dfSEXP);
    rcpp_result_gen = Rcpp::wrap(load_msdial_results(df));
    return rcpp_result_gen;
END_RCPP
}
// read_MSDIAL_file
DataFrame read_MSDIAL_file(String fh);
RcppExport SEXP _wSIMCity_read_MSDIAL_file(SEXP fhSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type fh(fhSEXP);
    rcpp_result_gen = Rcpp::wrap(read_MSDIAL_file(fh));
    return rcpp_result_gen;
END_RCPP
}
// read_list_MSDIAL_files
DataFrame read_list_MSDIAL_files(StringVector sample_file_list);
RcppExport SEXP _wSIMCity_read_list_MSDIAL_files(SEXP sample_file_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< StringVector >::type sample_file_list(sample_file_listSEXP);
    rcpp_result_gen = Rcpp::wrap(read_list_MSDIAL_files(sample_file_list));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_SearchResult();

static const R_CallMethodDef CallEntries[] = {
    {"_wSIMCity_ppmErr", (DL_FUNC) &_wSIMCity_ppmErr, 2},
    {"_wSIMCity_getMassTolRange", (DL_FUNC) &_wSIMCity_getMassTolRange, 2},
    {"_wSIMCity_dlaplace", (DL_FUNC) &_wSIMCity_dlaplace, 3},
    {"_wSIMCity_weight_laplace", (DL_FUNC) &_wSIMCity_weight_laplace, 4},
    {"_wSIMCity_load_msdial_results", (DL_FUNC) &_wSIMCity_load_msdial_results, 1},
    {"_wSIMCity_read_MSDIAL_file", (DL_FUNC) &_wSIMCity_read_MSDIAL_file, 1},
    {"_wSIMCity_read_list_MSDIAL_files", (DL_FUNC) &_wSIMCity_read_list_MSDIAL_files, 1},
    {"_rcpp_module_boot_SearchResult", (DL_FUNC) &_rcpp_module_boot_SearchResult, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_wSIMCity(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
