# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @name ppmErr
#' @title Calculate ppm error for a given mass
#'
#' @description This function compares 2 masses and computes the ppm error between them,
#' @param m a double number, the experimental mass
#' @param m0 a double number, the theoretical mass
#' @export
#' @return double number the ppm error
#' @examples
#' ppmErr(490.1944,490.1946)
#'  -0.4080012
ppmErr <- function(m, m0) {
    .Call('_wSIMCity_ppmErr', PACKAGE = 'wSIMCity', m, m0)
}

#' @name getMassTolRange
#' @title Get mass tolerance range in ppm
#'
#' @description  Generates the tolerance window in Da for a given ppm value and mass
#' @param m a double number, the mass
#' @param ppm a double number, the user provided ppm tol window
#' @export
#' @return vector of numeric values containing min and max range in Da
#' @examples
#' getMassTolRange(m = 490.1946,ppm = 5)
#' 490.1921 490.1971
getMassTolRange <- function(m, ppm) {
    .Call('_wSIMCity_getMassTolRange', PACKAGE = 'wSIMCity', m, ppm)
}

#' @name dlaplace
#' @title Probability density function: Laplace
#'
#' @description  Generates the tolerance window in Da for a given ppm value and mass
#' @param X numeric vector of values
#' @param m numeric the mode of the distribution
#' @param b numeric scale parameter
#' @export
#' @return vector of numeric values containing density values
#' @examples
#' x <- seq(-10,10,by = 0.001)
#' d_lap <- dlaplace(x,m=0,b = 1)
#' plot(x,d_lap, type = "l")
dlaplace <- function(X, m, b) {
    .Call('_wSIMCity_dlaplace', PACKAGE = 'wSIMCity', X, m, b)
}

#' @name weight_laplace
#' @title Calculate weight with Laplace assumption.
#'
#' @description  Assigned a weight to the distribution of X values given expected instrument performance.
#' For example, dM is the input X values, tol is a tolderance in ppm, and  boost is the multiplier.
#' @param dM vector or numeric the vector of measurement errors
#' @param tol numeric the ppm tolerance of the instrument
#' @param boost numeric the boost value (0-2)
#' @param mu numeric the mean of the laplace distribution
#'
#' @return numeric or vector the weighted value(S).
#' @export
#'
#' @examples 
#' weight_laplace(dM,mu=0.1, tol = 5, boost = 2)
weight_laplace <- function(dM, mu, tol, boost) {
    .Call('_wSIMCity_weight_laplace', PACKAGE = 'wSIMCity', dM, mu, tol, boost)
}

#' @export
load_msdial_results <- function(df) {
    .Call('_wSIMCity_load_msdial_results', PACKAGE = 'wSIMCity', df)
}

#' @export
read_MSDIAL_file <- function(fh) {
    .Call('_wSIMCity_read_MSDIAL_file', PACKAGE = 'wSIMCity', fh)
}

#' @export
read_list_MSDIAL_files <- function(sample_file_list) {
    .Call('_wSIMCity_read_list_MSDIAL_files', PACKAGE = 'wSIMCity', sample_file_list)
}

